#!/usr/bin/env bash
# shellcheck disable=SC1091
. "$(dirname "$0")/../lib/common.sh"

# 10-llmdocs — Make the llmdocs framework repo-agnostically available
# on the host.
#
# llmdocs/ is a stdlib-only Python framework for turning upstream
# Sphinx/Markdown/XML docs into LLM-friendly markdown. It ships with
# this repo under user-bootstrap/llmdocs/ and is meant to be reused
# across any docs-source project on the host — i.e., repo-agnostic.
#
# This step installs a single thin wrapper at $HOME/.local/bin/llmdocs
# that invokes `uv run --project <llmdocs dir> python -m llmdocs …`,
# so callers do not need to know the absolute path to the framework.
#
# Idempotent: rewrites the wrapper on every run (the path could have
# changed if the bootstrap repo was relocated) but does not touch
# $HOME/.local/bin/llmdocs beyond installing it.
#
# Run as the deploy user (./user-bootstrap/init.sh 10-llmdocs).

LLMDOCS_ROOT="$EE_ROOT/llmdocs"
WRAPPER="$HOME/.local/bin/llmdocs"

if [[ ! -d "$LLMDOCS_ROOT" ]]; then
  echo "ERROR: llmdocs/ not found at ${LLMDOCS_ROOT}" >&2
  echo "       user-bootstrap/llmdocs/ must exist alongside init.sh." >&2
  exit 1
fi

mkdir -p "$HOME/.local/bin"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by 10-llmdocs — wrapper for the llmdocs framework at
# ${LLMDOCS_ROOT}. Re-run user-bootstrap/10-llmdocs to refresh.
exec uv run --project "${LLMDOCS_ROOT}" python -m llmdocs "\$@"
EOF
chmod +x "$WRAPPER"

echo "Installed llmdocs wrapper at ${WRAPPER}"
echo "  -> llmdocs framework: ${LLMDOCS_ROOT}"
echo "Run 'llmdocs --help' to list available commands."
