#!/usr/bin/env bash
# shellcheck disable=SC1091
. "$(dirname "$0")/../lib/common.sh"

# 40-profile — Install the bootstrap-managed PATH block into the
# deploy user's ~/.profile.
#
# Why root tier: the deploy user's login-shell environment is part of
# "configuring the deploy user account" — same concern as
# 10-create-deploy-user, 20-groups, and 30-passwordless-sudo. The
# user-tier steps (10-llmdocs, 20-python, 30-kilo-session-report)
# only need ~/.local/bin/ on PATH for their wrappers to be callable;
# this PATH block is the prerequisite that makes that work without
# hand-edits on every new host.
#
# What it does: ensures ~/.local/bin and ~/.kilo/bin are on PATH for
# login shells. The block is a tight for-loop guarded with case
# matches so re-runs are no-ops, mirroring the per-dir guards in
# /etc/skel/.profile and ee/.envrc.
#
# What it does NOT do: it does not touch ~/.bashrc, the Go toolchain
# (ee-monorepo concern, sourced from ~/.bashrc via
# ee/scripts/lib/env.sh), or shell completions. Those belong to the
# repos that own them.
#
# Idempotency: the snippet is wrapped in stable BEGIN/END markers.
# Re-running with the same snippet content is a no-op; re-running with
# an updated snippet replaces just the marker block. Anything outside
# the markers (the stock Debian preamble, ~/bin block, Go env, etc.)
# is preserved verbatim.
#
# Run as root (sudo ./init.sh 40-profile).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SNIPPET_FILE="${SCRIPT_DIR}/profile.snippet"
MARKER_BEGIN='# --- BEGIN bootstrap-managed PATH block (do not edit between these lines) ---'
MARKER_END='# --- END bootstrap-managed PATH block ---'

: "${SUDO_USER:?must run under sudo (e.g., sudo ./init.sh)}"
TARGET_USER="$SUDO_USER"
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
TARGET_GROUP="$(id -gn "$TARGET_USER")"
PROFILE="${TARGET_HOME}/.profile"

if [[ ! -f "$SNIPPET_FILE" ]]; then
  echo "ERROR: snippet not found at ${SNIPPET_FILE}" >&2
  exit 1
fi

# /etc/skel/.profile is normally copied by `useradd -m`; the home dir
# is the only hard requirement.
if [[ ! -d "$TARGET_HOME" ]]; then
  echo "ERROR: target home ${TARGET_HOME} does not exist; cannot edit .profile." >&2
  exit 1
fi

# If the deploy user has set up bash to skip .profile (i.e., created
# ~/.bash_profile or ~/.bash_login), warn but do not abort. The block
# will land in .profile and the user can move it manually if needed.
for skip in "$TARGET_HOME/.bash_profile" "$TARGET_HOME/.bash_login"; do
  if [[ -f "$skip" ]]; then
    echo "WARNING: ${skip##*/} exists — bash will NOT source ~/.profile for login shells." >&2
    echo "         The bootstrap PATH block will not take effect until the snippet is also" >&2
    echo "         added to ${skip##*/}, or that file is removed." >&2
  fi
done

SNIPPET_CONTENT="$(cat "$SNIPPET_FILE")"

# ---------------------------------------------------------------------------
# Case 1: ~/.profile does not exist — create it with just the marker block.
# ---------------------------------------------------------------------------

if [[ ! -f "$PROFILE" ]]; then
  echo "==> ${PROFILE} does not exist; creating with the bootstrap PATH block."
  {
    echo "# ${TARGET_USER}'s login shell profile (generated by 40-profile)"
    echo "$MARKER_BEGIN"
    printf '%s\n' "$SNIPPET_CONTENT"
    echo "$MARKER_END"
  } > "$PROFILE"
  chown "$TARGET_USER":"$TARGET_GROUP" "$PROFILE"
  chmod 0644 "$PROFILE"
  echo "==> Wrote ${PROFILE} (owner ${TARGET_USER}:${TARGET_GROUP})."
  exit 0
fi

# ---------------------------------------------------------------------------
# Case 2: ~/.profile exists — look for the marker pair.
# ---------------------------------------------------------------------------

has_begin=0
has_end=0
grep -Fq "$MARKER_BEGIN" "$PROFILE" && has_begin=1
grep -Fq "$MARKER_END"   "$PROFILE" && has_end=1

if (( has_begin )) && (( has_end )); then
  existing_block="$(awk -v b="$MARKER_BEGIN" -v e="$MARKER_END" '
    $0 == b { capture = 1; next }
    $0 == e { capture = 0; next }
    capture  { print }
  ' "$PROFILE")"
  if [[ "$existing_block" == "$SNIPPET_CONTENT" ]]; then
    echo "==> ${PROFILE} — bootstrap PATH block already up to date; skipping."
    exit 0
  fi
  mode="replace"
elif (( has_begin )) || (( has_end )); then
  echo "ERROR: ${PROFILE} contains only one of the bootstrap markers — refusing to edit." >&2
  echo "       Manually remove the lone marker (${MARKER_BEGIN}" >&2
  echo "       or ${MARKER_END}) and re-run, or remove both markers and re-run." >&2
  exit 1
else
  mode="append"
fi

# ---------------------------------------------------------------------------
# Apply the change to a temp file, then `install` it into place so the
# ownership + mode are set atomically. A SIGINT / failure between the
# mktemp and the install leaves the user's real .profile untouched.
# ---------------------------------------------------------------------------

PROFILE_NEW="$(mktemp "${TARGET_HOME}/.profile.bootstrap.XXXXXX")"
# Belt-and-braces: also clean up on abnormal exit.
trap 'rm -f "$PROFILE_NEW"' EXIT

if [[ "$mode" == "replace" ]]; then
  # One awk pass: print everything outside the marker block, and
  # inject the new snippet in place of the BEGIN marker. The snippet
  # is passed in as a single string; split() on \n to print line-by-
  # line. (Trailing newline is handled by the loop's `print`.)
  awk -v begin="$MARKER_BEGIN" \
      -v end="$MARKER_END" \
      -v snippet="$SNIPPET_CONTENT" '
    BEGIN {
      n = split(snippet, lines, "\n")
    }
    {
      if ($0 == begin) {
        print begin
        for (i = 1; i <= n; i++) print lines[i]
        print end
        in_block = 1
        next
      }
      if ($0 == end) { in_block = 0; next }
      if (!in_block) print
    }
  ' "$PROFILE" > "$PROFILE_NEW"
else
  {
    cat "$PROFILE"
    # Make sure there is a newline between the previous content and
    # our marker, regardless of whether the file ended with one.
    if [[ -s "$PROFILE" ]] && [[ "$(tail -c1 "$PROFILE")" != $'\n' ]]; then
      echo ""
    fi
    echo ""
    echo "$MARKER_BEGIN"
    printf '%s\n' "$SNIPPET_CONTENT"
    echo "$MARKER_END"
  } > "$PROFILE_NEW"
fi

install -m 0644 -o "$TARGET_USER" -g "$TARGET_GROUP" "$PROFILE_NEW" "$PROFILE"
rm -f "$PROFILE_NEW"
trap - EXIT

if [[ "$mode" == "replace" ]]; then
  echo "==> ${PROFILE} — bootstrap PATH block updated (owner ${TARGET_USER}:${TARGET_GROUP})."
else
  echo "==> ${PROFILE} — bootstrap PATH block appended (owner ${TARGET_USER}:${TARGET_GROUP})."
fi
