#!/usr/bin/env bash
# shellcheck disable=SC1091
. "$(dirname "$0")/../lib/common.sh"

# 30-passwordless-sudo — Configure passwordless sudo for the invoking
# user.
#
# Reads commands from commands.txt and writes
# /etc/sudoers.d/99-<user>-passwordless. Idempotent: identical content
# is detected and the file is left alone. Syntax is validated via
# `visudo -c` before the file is committed; a bad file is removed
# before exiting 1.
#
# Run as root (sudo ./init.sh 30-passwordless-sudo).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMANDS_FILE="${SCRIPT_DIR}/commands.txt"
SUDOERS_FILE="/etc/sudoers.d/99-${SUDO_USER}-passwordless"

if [ ! -f "$COMMANDS_FILE" ]; then
  echo "commands.txt not found at ${COMMANDS_FILE}" >&2
  exit 0
fi

echo "==> Configuring passwordless sudo for ${SUDO_USER}..."

# Build sudoers content in memory to validate before writing.
SUDOERS_CONTENT="# Passwordless sudo for ${SUDO_USER} (generated by 30-passwordless-sudo)"
ENTRY_COUNT=0

while IFS= read -r line; do
  # Skip empty lines and comments.
  [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
  SUDOERS_CONTENT+=$'\n'"${SUDO_USER} ALL=(root) NOPASSWD: ${line}"
  ENTRY_COUNT=$((ENTRY_COUNT + 1))
done < "$COMMANDS_FILE"

if [ "$ENTRY_COUNT" -eq 0 ]; then
  echo "No commands found in ${COMMANDS_FILE} (empty or only comments)" >&2
  exit 0
fi

# Idempotency: skip if the file already has the correct content.
if [ -f "$SUDOERS_FILE" ]; then
  CURRENT_CONTENT="$(cat "$SUDOERS_FILE")"
  NEW_CONTENT="$(printf '%s\n' "$SUDOERS_CONTENT")"
  if [ "$CURRENT_CONTENT" = "$NEW_CONTENT" ]; then
    echo "==> ${SUDOERS_FILE} — already up to date, skipping."
    exit 0
  fi
fi

printf '%s\n' "$SUDOERS_CONTENT" > "$SUDOERS_FILE"
chmod 440 "$SUDOERS_FILE"
visudo -cf "$SUDOERS_FILE" || { rm -f "$SUDOERS_FILE"; echo "ERROR: invalid sudoers syntax"; exit 1; }

echo "==> Sudoers configured at ${SUDOERS_FILE} (${ENTRY_COUNT} entr(y/ies))"
