#!/usr/bin/env bash
# shellcheck disable=SC1091
. "$(dirname "$0")/../lib/common.sh"
. "$(dirname "$0")/../lib/user.sh"

# 30-passwordless-sudo — Configure passwordless sudo for the deploy
# user.
#
# Reads commands from commands.txt and writes
# /etc/sudoers.d/99-<user>-passwordless. Idempotent: identical content
# is detected and the file is left alone.
#
# Validate-before-activate: the file is built at a temp path, checked
# with `visudo -cf`, and only then `install`ed into /etc/sudoers.d/ —
# writing live and validating afterwards would leave ALL sudo broken in
# the window between write and validation failure.
#
# Also installs the root-owned no-argument maintenance wrappers from
# wrappers/ into /usr/local/sbin/ — commands.txt whitelists them for
# the deploy user's `maintain` @sudo tier.
#
# The deploy user is resolved via lib/user.sh, which rejects empty,
# "root", and names outside ^[a-z_][a-z0-9_-]{0,31}$ — a dot in the
# name would make sudo silently skip the /etc/sudoers.d/ file.
#
# Run as root (sudo ./init.sh 30-passwordless-sudo).

require_deploy_user

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMANDS_FILE="${SCRIPT_DIR}/commands.txt"
SUDOERS_FILE="/etc/sudoers.d/99-${DEPLOY_USER}-passwordless"

if [ ! -f "$COMMANDS_FILE" ]; then
  echo "commands.txt not found at ${COMMANDS_FILE}" >&2
  exit 0
fi

echo "==> Configuring passwordless sudo for ${DEPLOY_USER}..."

# Build sudoers content in memory to validate before writing.
SUDOERS_CONTENT="# Passwordless sudo for ${DEPLOY_USER} (generated by 30-passwordless-sudo)"
ENTRY_COUNT=0

while IFS= read -r line; do
  # Skip empty lines and comments.
  [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
  SUDOERS_CONTENT+=$'\n'"${DEPLOY_USER} ALL=(root) NOPASSWD: ${line}"
  ENTRY_COUNT=$((ENTRY_COUNT + 1))
done < "$COMMANDS_FILE"

if [ "$ENTRY_COUNT" -eq 0 ]; then
  echo "No commands found in ${COMMANDS_FILE} (empty or only comments)" >&2
  exit 0
fi

# Idempotency: skip if the file already has the correct content.
if [ -f "$SUDOERS_FILE" ] && [ "$(cat "$SUDOERS_FILE")" = "$(printf '%s\n' "$SUDOERS_CONTENT")" ]; then
  echo "==> ${SUDOERS_FILE} — already up to date, skipping."
else
  # Validate at a temp path, then install atomically — the live file is
  # never in an unvalidated state. The temp file lives in sudoers.d
  # itself (same filesystem) with a dot-containing name, which sudo
  # ignores even if a crash leaves it behind.
  TMP_SUDOERS="$(mktemp "/etc/sudoers.d/.99-${DEPLOY_USER}-passwordless.XXXXXX")"
  trap 'rm -f "$TMP_SUDOERS"' EXIT
  printf '%s\n' "$SUDOERS_CONTENT" > "$TMP_SUDOERS"
  chmod 0440 "$TMP_SUDOERS"
  if ! visudo -cf "$TMP_SUDOERS"; then
    echo "ERROR: invalid sudoers syntax — ${SUDOERS_FILE} left unchanged." >&2
    exit 1
  fi
  install -m 0440 -o root -g root "$TMP_SUDOERS" "$SUDOERS_FILE"
  rm -f "$TMP_SUDOERS"
  trap - EXIT
  echo "==> Sudoers configured at ${SUDOERS_FILE} (${ENTRY_COUNT} entr(y/ies))"
fi

# ---------------------------------------------------------------------------
# Root-owned maintenance wrappers (whitelisted in commands.txt).
# ---------------------------------------------------------------------------

for wrapper in drop-caches prune-text-logs; do
  src="${SCRIPT_DIR}/wrappers/${wrapper}"
  dst="/usr/local/sbin/${wrapper}"
  if [[ -f "$dst" ]] && cmp -s "$src" "$dst"; then
    echo "ok:   ${dst} (unchanged)"
  else
    install -m 0755 -o root -g root "$src" "$dst"
    echo "installed: ${dst}"
  fi
done
