#!/usr/bin/env bash
# 12-bashrc — Ensure ~/.local/bin and ~/.kilo/bin are on PATH for non-login
# interactive shells.
#
# User tier: runs as the deploy user (non-root).
# The root-tier 40-profile step writes PATH into ~/.profile, but that is only
# sourced by login shells. VS Code integrated terminals, `bash` without `-l`,
# and most tool-launched shells are non-login — they never see ~/.profile.
# This step writes the same idempotent PATH block into ~/.bashrc, which is
# sourced by all interactive non-login bash shells (see bash(1) INVOCATION).
#
# On macOS 40-profile is Linux-only, so nothing else puts ~/.local/bin and
# ~/.kilo/bin on PATH for zsh — this step is the concrete substitute: it also
# writes the same block to ~/.zshrc and ~/.zprofile on Darwin.
#
# Idempotent: the block is bounded by stable BEGIN/END markers so re-running
# is a no-op and an updated snippet replaces only the marker block.
#
# Run as the deploy user (./user/init.sh 12-bashrc).

set -euo pipefail

# shellcheck source=../lib/common.sh
. "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

MARKER_BEGIN='# --- BEGIN bootstrap-managed PATH block (do not edit between these lines) ---'
MARKER_END='# --- END bootstrap-managed PATH block ---'

# The snippet is intentionally a literal heredoc — the convenience variables
# and `case` / `unset` patterns match the profile.snippet in
# init.d/40-profile/ exactly so the two blocks stay in sync.
# shellcheck disable=SC2016
SNIPPET_CONTENT='# Idempotent: each directory is added to PATH only if not already
# present, so re-running this block is a no-op. Designed to be wrapped
# in BEGIN/END markers so the bootstrap step can detect and update it.
for _bp_dir in "$HOME/.local/bin" "$HOME/.kilo/bin"; do
    if [ -d "$_bp_dir" ]; then
        case ":$PATH:" in
            *":$_bp_dir:"*) ;;
            *) PATH="$_bp_dir:$PATH" ;;
        esac
    fi
done
unset _bp_dir
export PATH'

# Target rc files: ~/.bashrc everywhere; on macOS also ~/.zshrc (interactive
# shells) and ~/.zprofile (login shells — the macOS substitute for the
# Linux-only root-tier 40-profile step).
TARGETS=("$HOME/.bashrc")
if [[ "$(uname -s)" == "Darwin" ]]; then
  TARGETS+=("$HOME/.zshrc" "$HOME/.zprofile")
fi

process_rc_file() {
  local rc_file="$1"

  if [[ ! -f "$rc_file" ]]; then
    echo "==> ${rc_file} does not exist; creating with the bootstrap PATH block."
    {
      echo "# $(id -un)'s ${rc_file##*/} (generated by 12-bashrc)"
      echo "$MARKER_BEGIN"
      printf '%s\n' "$SNIPPET_CONTENT"
      echo "$MARKER_END"
    } > "$rc_file"
    chmod 0644 "$rc_file"
    echo "==> Wrote ${rc_file}."
    return 0
  fi

  # Detect existing marker pair.
  local has_begin=0 has_end=0
  grep -Fq "$MARKER_BEGIN" "$rc_file" && has_begin=1
  grep -Fq "$MARKER_END"   "$rc_file" && has_end=1

  local mode
  if (( has_begin )) && (( has_end )); then
    local existing_block
    existing_block="$(awk -v b="$MARKER_BEGIN" -v e="$MARKER_END" '
      $0 == b { capture = 1; next }
      $0 == e { capture = 0; next }
      capture  { print }
    ' "$rc_file")"
    if [[ "$existing_block" == "$SNIPPET_CONTENT" ]]; then
      echo "==> ${rc_file} — bootstrap PATH block already up to date; skipping."
      return 0
    fi
    mode="replace"
  elif (( has_begin )) || (( has_end )); then
    echo "ERROR: ${rc_file} contains only one of the bootstrap markers — refusing to edit." >&2
    exit 1
  else
    mode="append"
  fi

  local rc_new
  rc_new="$(mktemp "${rc_file}.bootstrap.XXXXXX")"
  # shellcheck disable=SC2064
  trap "rm -f '$rc_new'" EXIT

  if [[ "$mode" == "replace" ]]; then
    awk -v begin="$MARKER_BEGIN" \
        -v end="$MARKER_END" \
        -v snippet="$SNIPPET_CONTENT" '
      BEGIN {
        n = split(snippet, lines, "\n")
      }
      {
        if ($0 == begin) {
          print begin
          for (i = 1; i <= n; i++) print lines[i]
          print end
          in_block = 1
          next
        }
        if ($0 == end) { in_block = 0; next }
        if (!in_block) print
      }
    ' "$rc_file" > "$rc_new"
  else
    {
      cat "$rc_file"
      if [[ -s "$rc_file" ]] && [[ "$(tail -c1 "$rc_file")" != $'\n' ]]; then
        echo ""
      fi
      echo ""
      echo "$MARKER_BEGIN"
      printf '%s\n' "$SNIPPET_CONTENT"
      echo "$MARKER_END"
    } > "$rc_new"
  fi

  mv "$rc_new" "$rc_file"
  trap - EXIT
  # mktemp creates 0600; the create path above uses 0644 — normalize so
  # the two paths leave the same mode.
  chmod 0644 "$rc_file"

  if [[ "$mode" == "replace" ]]; then
    echo "==> ${rc_file} — bootstrap PATH block updated."
  else
    echo "==> ${rc_file} — bootstrap PATH block appended."
  fi
}

for rc_file in "${TARGETS[@]}"; do
  process_rc_file "$rc_file"
done
