#!/usr/bin/env bash
# 12-bashrc — Ensure ~/.local/bin and ~/.kilo/bin are on PATH for non-login
# interactive shells.
#
# User tier: runs as the deploy user (non-root).
# The root-tier 40-profile step writes PATH into ~/.profile, but that is only
# sourced by login shells. VS Code integrated terminals, `bash` without `-l`,
# and most tool-launched shells are non-login — they never see ~/.profile.
# This step writes the same idempotent PATH block into ~/.bashrc, which is
# sourced by all interactive non-login bash shells (see bash(1) INVOCATION).
#
# Idempotent: the block is bounded by stable BEGIN/END markers so re-running
# is a no-op and an updated snippet replaces only the marker block.
#
# Run as the deploy user (./user/init.sh 12-bashrc).

set -euo pipefail

# shellcheck source=../lib/common.sh
. "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

BASHRC="$HOME/.bashrc"
MARKER_BEGIN='# --- BEGIN bootstrap-managed PATH block (do not edit between these lines) ---'
MARKER_END='# --- END bootstrap-managed PATH block ---'

# The snippet is intentionally a literal heredoc — the convenience variables
# and `case` / `unset` patterns match the profile.snippet in
# init.d/40-profile/ exactly so the two blocks stay in sync.
SNIPPET_CONTENT='# Idempotent: each directory is added to PATH only if not already
# present, so re-running this block is a no-op. Designed to be wrapped
# in BEGIN/END markers so the bootstrap step can detect and update it.
for _bp_dir in "$HOME/.local/bin" "$HOME/.kilo/bin"; do
    if [ -d "$_bp_dir" ]; then
        case ":$PATH:" in
            *":$_bp_dir:"*) ;;
            *) PATH="$_bp_dir:$PATH" ;;
        esac
    fi
done
unset _bp_dir
export PATH'

if [[ ! -f "$BASHRC" ]]; then
  echo "==> ${BASHRC} does not exist; creating with the bootstrap PATH block."
  {
    echo "# ${USER}'s bashrc (generated by 12-bashrc)"
    echo "$MARKER_BEGIN"
    printf '%s\n' "$SNIPPET_CONTENT"
    echo "$MARKER_END"
  } > "$BASHRC"
  chmod 0644 "$BASHRC"
  echo "==> Wrote ${BASHRC}."
  exit 0
fi

# Detect existing marker pair.
has_begin=0
has_end=0
grep -Fq "$MARKER_BEGIN" "$BASHRC" && has_begin=1
grep -Fq "$MARKER_END"   "$BASHRC" && has_end=1

if (( has_begin )) && (( has_end )); then
  existing_block="$(awk -v b="$MARKER_BEGIN" -v e="$MARKER_END" '
    $0 == b { capture = 1; next }
    $0 == e { capture = 0; next }
    capture  { print }
  ' "$BASHRC")"
  if [[ "$existing_block" == "$SNIPPET_CONTENT" ]]; then
    echo "==> ${BASHRC} — bootstrap PATH block already up to date; skipping."
    exit 0
  fi
  mode="replace"
elif (( has_begin )) || (( has_end )); then
  echo "ERROR: ${BASHRC} contains only one of the bootstrap markers — refusing to edit." >&2
  exit 1
else
  mode="append"
fi

BASHRC_NEW="$(mktemp "${HOME}/.bashrc.bootstrap.XXXXXX")"
# shellcheck disable=SC2064
trap 'rm -f "$BASHRC_NEW"' EXIT

if [[ "$mode" == "replace" ]]; then
  awk -v begin="$MARKER_BEGIN" \
      -v end="$MARKER_END" \
      -v snippet="$SNIPPET_CONTENT" '
    BEGIN {
      n = split(snippet, lines, "\n")
    }
    {
      if ($0 == begin) {
        print begin
        for (i = 1; i <= n; i++) print lines[i]
        print end
        in_block = 1
        next
      }
      if ($0 == end) { in_block = 0; next }
      if (!in_block) print
    }
  ' "$BASHRC" > "$BASHRC_NEW"
else
  {
    cat "$BASHRC"
    if [[ -s "$BASHRC" ]] && [[ "$(tail -c1 "$BASHRC")" != $'\n' ]]; then
      echo ""
    fi
    echo ""
    echo "$MARKER_BEGIN"
    printf '%s\n' "$SNIPPET_CONTENT"
    echo "$MARKER_END"
  } > "$BASHRC_NEW"
fi

mv "$BASHRC_NEW" "$BASHRC"
trap - EXIT

if [[ "$mode" == "replace" ]]; then
  echo "==> ${BASHRC} — bootstrap PATH block updated."
else
  echo "==> ${BASHRC} — bootstrap PATH block appended."
fi
