#!/usr/bin/env bash
# shellcheck disable=SC1091
. "$(dirname "$0")/../lib/common.sh"

# 30-kilo-session-report — Install a wrapper for kilo-session-report.
#
# kilo-session-report.py is a stdlib-only Python utility that fetches
# Kilo sessions via the local `kilo` CLI (installed by 20-tooling) and
# emits a compact LLM-friendly report of context-bloat hotspots and
# tool-call failures. The script itself does not need installation —
# this step just puts a thin wrapper at $HOME/.local/bin/kilo-session-
# report so it can be invoked by name.
#
# The wrapper invokes `uv run --script` against the .py file so the
# PEP 723 inline metadata declares the Python version (>=3.11) the
# script expects. No venv or requirements.txt is needed.
#
# Idempotent: rewrites the wrapper on every run.
#
# Run as the deploy user (./user-bootstrap/init.sh 30-kilo-session-report).

SCRIPT="$EE_ROOT/kilo-session-report.py"
WRAPPER="$HOME/.local/bin/kilo-session-report"

if [[ ! -f "$SCRIPT" ]]; then
  echo "ERROR: kilo-session-report.py not found at ${SCRIPT}" >&2
  echo "       user-bootstrap/kilo-session-report.py must exist alongside init.sh." >&2
  exit 1
fi

if ! command -v uv >/dev/null 2>&1 && [[ ! -x "$HOME/.local/bin/uv" ]]; then
  echo "ERROR: uv is required to run kilo-session-report but was not found." >&2
  echo "       Re-run after 20-tooling installs uv." >&2
  exit 1
fi

mkdir -p "$HOME/.local/bin"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by 30-kilo-session-report — wrapper for kilo-session-report.py
# at ${SCRIPT}. Re-run user-bootstrap/30-kilo-session-report to refresh.
exec uv run --script "${SCRIPT}" "\$@"
EOF
chmod +x "$WRAPPER"

echo "Installed kilo-session-report wrapper at ${WRAPPER}"
echo "  -> script: ${SCRIPT}"
echo "Run 'kilo-session-report --help' for usage."
